import { Container } from '@/components/shared/Container'
import { Header } from '@/components/shared/Header'
import { Navbar } from '@/components/shared/Navbar'
import '../styles/globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='bg-slate-700'>
        <Header />
        <Container>
          {children}
        </Container>
      </body>
    </html>
  )
}
